# SPDX-License-Identifier: GPL-2.0
# Copyright IBM Corp. 2014,2018

obj-m		+= testskel.o
obj-m		+= skeytorture.o
obj-m		+= skeymigration.o
obj-m		+= intloop.o
obj-m		+= sigptest.o
obj-m		+= exittime.o
obj-m		+= cmmamigration.o
obj-m		+= cmmatorture.o
